from pathlib import Path
import hashlib
import subprocess
src=Path('index.html')
out=src
raw=src.read_bytes()
actual=hashlib.sha256(raw).hexdigest()
expected='6889fa51dfe2139ee9ce48b2b83c461decee1bc1ea121a81333d8b5fb63d73c1'
if actual!=expected: raise SystemExit(f'unexpected source hash: {actual}')
s=raw.decode('utf-8')
s=s.replace('V9-5','V9-6')

needle='<script src="https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js"></script>'
repl='<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>\n'+needle
assert needle in s
s=s.replace(needle,repl,1)
css='''\n/* V9-6: QR + classroom sharing */\n.qr-live-box{display:grid;place-items:center;margin:13px auto 8px;min-height:172px}.qr-live-box>div{background:#fff;border:1px solid #d7e2e8;border-radius:14px;padding:8px;min-width:172px;min-height:172px;display:grid;place-items:center}.qr-live-box img,.qr-live-box canvas{display:block;max-width:156px!important;width:156px!important;height:156px!important}.qr-fallback{font-size:11px;color:#6a7e8e;text-align:center;line-height:1.5;padding:14px}.share-tools{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px}.share-tools .wide{grid-column:1/-1}.share-board-bg{position:fixed;inset:0;z-index:1200;background:linear-gradient(145deg,#0f2e48,#183e59 58%,#255b76);display:grid;place-items:center;padding:24px}.share-board{width:min(980px,96vw);min-height:min(690px,92vh);background:#fff;border-radius:30px;padding:34px;display:grid;grid-template-columns:1.1fr .9fr;gap:34px;align-items:center;box-shadow:0 28px 80px rgba(0,0,0,.32);position:relative}.share-board-close{position:absolute;right:20px;top:18px;border:0;background:#eef3f6;border-radius:999px;width:42px;height:42px;font-size:20px;cursor:pointer}.share-board-copy small{display:block;color:#6d8090;font-size:13px;font-weight:800;margin-bottom:10px}.share-board-copy h2{font-size:42px;line-height:1.14;margin:0 0 12px;letter-spacing:-.035em}.share-code{font-size:74px;line-height:1;font-weight:950;letter-spacing:.13em;color:#123a59;margin:26px 0 22px;white-space:nowrap}.share-url-big{font-size:16px;line-height:1.45;color:#506b7e;word-break:break-all;background:#f3f7f9;border-radius:13px;padding:12px 14px}.share-board-qr{display:grid;place-items:center}.share-board-qr>div{background:#fff;border:2px solid #c9dbe6;border-radius:22px;padding:18px;min-width:270px;min-height:270px;display:grid;place-items:center}.share-board-qr img,.share-board-qr canvas{width:236px!important;height:236px!important;display:block}.share-board-tip{font-size:13px;color:#667d8d;text-align:center;margin-top:12px}.copy-code-btn{font-variant-numeric:tabular-nums}@media(max-width:760px){.share-tools{grid-template-columns:1fr}.share-tools .wide{grid-column:auto}.share-board{grid-template-columns:1fr;gap:18px;padding:26px 18px;overflow:auto}.share-board-copy h2{font-size:30px}.share-code{font-size:48px}.share-board-qr>div{min-width:220px;min-height:220px}.share-board-qr img,.share-board-qr canvas{width:190px!important;height:190px!important}}\n'''
s=s.replace('</style>',css+'</style>',1)
old="studentMode:(params.has('join')||params.get('student')==='1'),studentJoin:null};"
new="studentMode:(params.has('join')||params.get('student')==='1'),studentJoin:null,shareBoard:false};"
assert old in s;s=s.replace(old,new,1)
anchor="function studentJoinURL(code){return `${location.origin}${location.pathname}?join=${encodeURIComponent(code)}`}\n";assert anchor in s
helpers=anchor+"""function renderJoinQRCodes(){document.querySelectorAll('[data-qr-url]').forEach(el=>{const text=el.getAttribute('data-qr-url')||'';if(!text)return;el.innerHTML='';if(typeof QRCode==='undefined'){el.innerHTML='<div class=\"qr-fallback\">QR 모듈을 불러오지 못했습니다.<br>참여 코드나 주소를 사용해 주세요.</div>';return}try{new QRCode(el,{text,width:236,height:236,colorDark:'#132841',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M})}catch(e){console.error(e);el.innerHTML='<div class=\"qr-fallback\">QR 생성에 실패했습니다.<br>참여 코드나 주소를 사용해 주세요.</div>'}})}\nfunction shareBoardHTML(){const sess=state.sessionSetup;if(!state.shareBoard||sess?.mode!=='firebase')return '';const url=studentJoinURL(sess.code||'');return `<div class=\"share-board-bg\"><section class=\"share-board\"><button class=\"share-board-close\" data-action=\"shareBoardClose\" aria-label=\"닫기\">✕</button><div class=\"share-board-copy\"><small>Drama Reflect Builder · 학생 참여</small><h2>${esc(state.activity?.title||sess.activityTitle||'수업')}</h2><div class=\"share-code\">${esc(sess.code||'------')}</div><div class=\"share-url-big\">${esc(url)}</div><div class=\"session-actions\" style=\"margin-top:14px\"><button class=\"btn primary copy-code-btn\" data-action=\"copyJoinCode\">참여 코드 복사</button><button class=\"btn\" data-action=\"copyJoinLink\">주소 복사</button></div></div><div class=\"share-board-qr\"><div data-qr-url=\"${esc(url)}\"></div><div class=\"share-board-tip\">휴대폰 카메라로 QR을 찍거나<br>6자리 참여 코드를 입력하세요.</div></div></section></div>`}\n"""
s=s.replace(anchor,helpers,1)
old="""${online?`<div class=\"share-url\">${esc(share)}</div><div class=\"session-actions\"><button class=\"btn soft\" data-action=\"copyJoinLink\">참여 주소 복사</button></div>`:`<div style=\"height:12px\"></div><h3>학생 참여 주소 · QR</h3><div class=\"qr-placeholder\"><span>QR 자리<br><b>실시간 수업에서 활성화</b></span></div>`}"""
new="""${online?`<div class=\"qr-live-box\"><div data-qr-url=\"${esc(share)}\"></div></div><div class=\"share-url\">${esc(share)}</div><div class=\"share-tools\"><button class=\"btn soft copy-code-btn\" data-action=\"copyJoinCode\">참여 코드 복사</button><button class=\"btn soft\" data-action=\"copyJoinLink\">참여 주소 복사</button><button class=\"btn primary wide\" data-action=\"shareBoardOpen\">▣ 교실 전체화면 참여 안내</button></div>`:`<div style=\"height:12px\"></div><h3>학생 참여 주소 · QR</h3><div class=\"qr-placeholder\"><span>QR 자리<br><b>실시간 수업에서 활성화</b></span></div>`}"""
assert old in s;s=s.replace(old,new,1)
old="function render(){if(state.studentMode){document.getElementById('app').innerHTML=studentJoinHTML();bind();return}document.getElementById('app').innerHTML=(state.screen==='home'?home():editor())+(state.overview?overviewHTML():'')+(state.flowPreview?flowPreviewHTML():'')+(state.sessionSetup&&!state.facilitatorPreview?sessionSetupHTML():'')+(state.facilitatorPreview?facilitatorPreviewHTML():'');bind()}"
new="function render(){if(state.studentMode){document.getElementById('app').innerHTML=studentJoinHTML();bind();renderJoinQRCodes();return}document.getElementById('app').innerHTML=(state.screen==='home'?home():editor())+(state.overview?overviewHTML():'')+(state.flowPreview?flowPreviewHTML():'')+(state.sessionSetup&&!state.facilitatorPreview?sessionSetupHTML():'')+(state.facilitatorPreview?facilitatorPreviewHTML():'')+(state.shareBoard?shareBoardHTML():'');bind();renderJoinQRCodes()}"
assert old in s;s=s.replace(old,new,1)
old=""" else if(a==='copyJoinLink'){const u=studentJoinURL(state.sessionSetup?.code||'');if(navigator.clipboard?.writeText)navigator.clipboard.writeText(u).then(()=>toast('참여 주소를 복사했습니다.')).catch(()=>toast(u));else toast(u)}\n else if(a==='studentJoinHome')"""
new=""" else if(a==='copyJoinCode'){const c=state.sessionSetup?.code||'';if(navigator.clipboard?.writeText)navigator.clipboard.writeText(c).then(()=>toast('참여 코드를 복사했습니다.')).catch(()=>toast(c));else toast(c)}\n else if(a==='copyJoinLink'){const u=studentJoinURL(state.sessionSetup?.code||'');if(navigator.clipboard?.writeText)navigator.clipboard.writeText(u).then(()=>toast('참여 주소를 복사했습니다.')).catch(()=>toast(u));else toast(u)}\n else if(a==='shareBoardOpen'){if(state.sessionSetup?.mode==='firebase'){state.shareBoard=true;render()}}\n else if(a==='shareBoardClose'){state.shareBoard=false;render()}\n else if(a==='studentJoinHome')"""
assert old in s;s=s.replace(old,new,1)
out.write_text(s,encoding='utf-8')
new_hash=hashlib.sha256(out.read_bytes()).hexdigest();expected_out='0959baca77cd648702b4f1f9cff110f1884796189998db8f7a627f58fb877068'
if new_hash!=expected_out: raise SystemExit(f'unexpected output hash: {new_hash}')
import re as _re
parts=_re.findall(r'<script(?: [^>]*)?>(.*?)</script>',s,flags=_re.S);Path('/tmp/drb_app.js').write_text(parts[-1],encoding='utf-8');subprocess.run(['node','--check','/tmp/drb_app.js'],check=True)
print(f'V9-6 applied: {len(s)} chars, sha256={new_hash}')
