from pathlib import Path
import hashlib
import subprocess
import re
src=Path('index.html')
out=src
raw=src.read_bytes()
actual=hashlib.sha256(raw).hexdigest()
expected='928c05ff80ae78fed81a1fe3a01cc3d71bd072e8c1f56d7e34852c82ccc83c49'
if actual!=expected: raise SystemExit(f'unexpected source hash: {actual}')
s=raw.decode('utf-8')

s=s.replace('V9-4','V9-5')
css='''\n/* V9-5: reconnect + recovery */\n.live-resume-card{margin:18px 0 0;border:1px solid #bcd7e7;background:linear-gradient(135deg,#f4fbff,#f7fbf8);border-radius:18px;padding:15px 16px;display:flex;justify-content:space-between;gap:14px;align-items:center;box-shadow:0 7px 18px rgba(31,73,98,.06)}\n.live-resume-card b{display:block;font-size:14px;margin-bottom:4px}.live-resume-card span{display:block;font-size:11px;color:#5e7688}.live-resume-actions{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}.recent-live-hint{font-size:10.5px;color:#6f8290;text-align:center;margin-top:8px}.reconnect-note{border:1px solid #cde2d6;background:#f2faf5;color:#3f6d54;border-radius:11px;padding:9px 10px;font-size:11px;line-height:1.5;margin-top:10px}\n@media(max-width:700px){.live-resume-card{align-items:stretch;flex-direction:column}.live-resume-actions{justify-content:stretch}.live-resume-actions .btn{flex:1}}\n'''
s=s.replace('</style>',css+'</style>',1)
old="""const STUDENT_LOCAL_PREFIX='drb_student_';\nfunction rememberStudentJoin(code,data){try{localStorage.setItem(STUDENT_LOCAL_PREFIX+code,JSON.stringify(data))}catch(_){}}\nfunction readStudentJoin(code){try{return JSON.parse(localStorage.getItem(STUDENT_LOCAL_PREFIX+code)||'null')}catch(_){return null}}\n"""
new="""const STUDENT_LOCAL_PREFIX='drb_student_';\nconst STUDENT_LAST_LOCAL_KEY='drb_student_last';\nconst TEACHER_SESSION_LOCAL_KEY='drb_teacher_firebase_session';\nfunction rememberStudentJoin(code,data){try{const saved={code,...data,rememberedAt:Date.now()};localStorage.setItem(STUDENT_LOCAL_PREFIX+code,JSON.stringify(saved));localStorage.setItem(STUDENT_LAST_LOCAL_KEY,JSON.stringify(saved))}catch(_){}}\nfunction readStudentJoin(code){try{return JSON.parse(localStorage.getItem(STUDENT_LOCAL_PREFIX+code)||'null')}catch(_){return null}}\nfunction readLastStudentJoin(){try{return JSON.parse(localStorage.getItem(STUDENT_LAST_LOCAL_KEY)||'null')}catch(_){return null}}\nfunction rememberTeacherSession(data){try{localStorage.setItem(TEACHER_SESSION_LOCAL_KEY,JSON.stringify({...data,rememberedAt:Date.now()}))}catch(_){}}\nfunction readTeacherSession(){try{return JSON.parse(localStorage.getItem(TEACHER_SESSION_LOCAL_KEY)||'null')}catch(_){return null}}\nfunction clearTeacherSession(){try{localStorage.removeItem(TEACHER_SESSION_LOCAL_KEY)}catch(_){}}\n"""
assert old in s;s=s.replace(old,new,1)
oldfrag="""state.sessionSetup={id:ref.id,firebaseSessionId:ref.id,activityId:state.activity.id,activityTitle:state.activity.title,blockIds:state.activity.blocks.map(b=>b.id),code,status:'draft',mode:'firebase',currentBlock:0,entryOpen:true,participants:[],responses:{},meetingHistory:[]};state.facilitatorPreview=false;subscribeTeacherFirebaseSession(ref.id);"""
newfrag="""state.sessionSetup={id:ref.id,firebaseSessionId:ref.id,activityId:state.activity.id,activityTitle:state.activity.title,blockIds:state.activity.blocks.map(b=>b.id),code,status:'draft',mode:'firebase',currentBlock:0,entryOpen:true,participants:[],responses:{},meetingHistory:[]};rememberTeacherSession({sessionId:ref.id,activityId:state.activity.id,activityTitle:state.activity.title,code,status:'draft'});state.facilitatorPreview=false;subscribeTeacherFirebaseSession(ref.id);"""
assert oldfrag in s;s=s.replace(oldfrag,newfrag,1)
oldfrag="""meetingHistory:Array.isArray(d.meetingHistory)?d.meetingHistory:(state.sessionSetup.meetingHistory||[])});render()"""
newfrag="""meetingHistory:Array.isArray(d.meetingHistory)?d.meetingHistory:(state.sessionSetup.meetingHistory||[])});rememberTeacherSession({sessionId,status:d.status||'draft',activityId:d.activityId||state.sessionSetup.activityId,activityTitle:d.activityTitle||state.sessionSetup.activityTitle,code:state.sessionSetup.code||''});render()"""
assert oldfrag in s;s=s.replace(oldfrag,newfrag,1)
anchor="async function updateFirebaseSession(patch){";assert anchor in s
resume_fn="""async function resumeFirebaseClass(){const saved=readTeacherSession();if(!saved?.sessionId){toast('이어볼 실시간 수업이 없습니다.');return}try{const teacher=await ensureTeacherAuth(),ref=fbDb.collection('sessions').doc(saved.sessionId),snap=await ref.get();if(!snap.exists){clearTeacherSession();toast('저장된 수업을 찾지 못했습니다.');return}const d=snap.data()||{};if(d.teacherUid!==teacher.uid){toast('이 수업을 만든 교사 계정으로 로그인해 주세요.');return}const activity=d.activity||getUser()?.activities?.[d.activityId];if(!activity?.blocks?.length){toast('수업 활동 정보를 불러오지 못했습니다.');return}state.activity=clone(activity);state.selected=state.activity.blocks[0]?.id||null;state.screen='editor';state.sessionSetup={id:ref.id,firebaseSessionId:ref.id,activityId:d.activityId||activity.id,activityTitle:d.activityTitle||activity.title,blockIds:Array.isArray(d.blockIds)?d.blockIds:activity.blocks.map(b=>b.id),code:saved.code||'',status:d.status||'draft',mode:'firebase',currentBlock:Number.isInteger(d.currentBlock)?d.currentBlock:0,entryOpen:!!d.entryOpen,participants:[],responses:{},meetingHistory:Array.isArray(d.meetingHistory)?d.meetingHistory:[]};state.facilitatorPreview=d.status==='running'||d.status==='ended';rememberTeacherSession({sessionId:ref.id,activityId:d.activityId||activity.id,activityTitle:d.activityTitle||activity.title,code:saved.code||'',status:d.status||'draft'});subscribeTeacherFirebaseSession(ref.id);render();toast(d.status==='ended'?'지난 수업 결과를 불러왔습니다.':'실시간 수업에 다시 연결했습니다.')}catch(e){console.error(e);toast(firebaseErrorMessage(e))}}\n"""
s=s.replace(anchor,resume_fn+anchor,1)
pat=r"async function joinFirebaseSession\(\)\{.*?\}\nfunction oneSelected";m=re.search(pat,s,flags=re.S);assert m
newjoin="""async function joinFirebaseSession(){const code=(document.querySelector('[data-student-code]')?.value||'').replace(/\\D/g,'').slice(0,6),name=(document.querySelector('[data-student-name]')?.value||'').trim().slice(0,20);if(code.length!==6){toast('6자리 참여 코드를 입력해 주세요.');return}if(!name){toast('이름을 입력해 주세요.');return}try{const user=await ensureAnonymousAuth(),codeSnap=await fbDb.collection('joinCodes').doc(code).get();if(!codeSnap.exists){toast('참여 코드를 찾지 못했습니다.');return}const sessionId=codeSnap.data().sessionId,sessionRef=fbDb.collection('sessions').doc(sessionId),partRef=sessionRef.collection('participants').doc(user.uid),partSnap=await partRef.get();let sessionSnap;try{sessionSnap=await sessionRef.get()}catch(e){if(e?.code==='permission-denied'&&!partSnap.exists){toast('학생 입장이 닫혔거나 종료된 수업입니다.');return}throw e}if(!sessionSnap.exists){toast('수업을 찾지 못했습니다.');return}const sd=sessionSnap.data()||{};if(partSnap.exists){const pd=partSnap.data()||{};await partRef.update({lastSeen:firebase.firestore.FieldValue.serverTimestamp()}).catch(()=>{});rememberStudentJoin(code,{sessionId,name:pd.name||name});attachStudentSession(sessionRef,user,{joined:true,sessionId,name:pd.name||name,activityTitle:sd.activityTitle||'수업',sessionStatus:sd.status||'draft',currentBlock:Number.isInteger(sd.currentBlock)?sd.currentBlock:0,activity:sd.activity||null,responses:{blocks:{}},participant:pd});toast('기존 수업으로 다시 연결했습니다.');return}if(sd.status==='ended'){toast('이미 종료된 수업입니다.');return}if(!sd.entryOpen){toast('현재 학생 입장이 닫혀 있습니다.');return}await partRef.set({uid:user.uid,name,role:'student',status:'waiting',currentBlock:0,joinedAt:firebase.firestore.FieldValue.serverTimestamp(),lastSeen:firebase.firestore.FieldValue.serverTimestamp()});rememberStudentJoin(code,{sessionId,name});attachStudentSession(sessionRef,user,{joined:true,sessionId,name,activityTitle:sd.activityTitle||'수업',sessionStatus:sd.status||'draft',currentBlock:Number.isInteger(sd.currentBlock)?sd.currentBlock:0,activity:sd.activity||null,responses:{blocks:{}},participant:null})}catch(e){console.error(e);toast(firebaseErrorMessage(e))}}\nfunction oneSelected"""
s=s[:m.start()]+newjoin+s[m.end():]
old="""const d=ss.data()||{},pd=ps.data()||{};attachStudentSession(ref,user,{joined:true""";new="""const d=ss.data()||{},pd=ps.data()||{};await ref.collection('participants').doc(user.uid).update({lastSeen:firebase.firestore.FieldValue.serverTimestamp()}).catch(()=>{});attachStudentSession(ref,user,{joined:true""";assert old in s;s=s.replace(old,new,1)
old="function studentJoinHTML(){const preset=(params.get('join')||'').replace(/\\D/g,'').slice(0,6),sj=state.studentJoin||{};";new="function studentJoinHTML(){const preset=(params.get('join')||'').replace(/\\D/g,'').slice(0,6),sj=state.studentJoin||{},last=readLastStudentJoin();";assert old in s;s=s.replace(old,new,1)
old='''<div class="student-join-actions"><button class="btn primary" data-action="firebaseStudentJoin">입장하기</button><button class="btn" data-action="studentJoinExit">교사용 화면으로 돌아가기</button></div><div class="auth-help">'''
new='''<div class="student-join-actions"><button class="btn primary" data-action="firebaseStudentJoin">입장하기</button>${last?.code?`<button class="btn soft" data-action="studentResumeRecent">최근 수업 ${esc(last.code)} 이어가기</button>`:''}<button class="btn" data-action="studentJoinExit">교사용 화면으로 돌아가기</button></div>${last?.code?`<div class="recent-live-hint">이 기기에서 참여했던 최근 수업이 저장되어 있습니다.</div>`:''}<div class="auth-help">''';assert old in s;s=s.replace(old,new,1)
anchor='function home(){';assert anchor in s
helper="""function teacherSessionResumeHTML(){const sess=readTeacherSession();if(!sess?.sessionId)return '';const ended=sess.status==='ended';return `<div class=\"live-resume-card\"><div><b>${ended?'지난 실시간 수업 결과가 남아 있습니다.':'진행 중이던 실시간 수업이 있습니다.'}</b><span>${esc(sess.activityTitle||'수업')} · 참여 코드 ${esc(sess.code||'------')}</span></div><div class=\"live-resume-actions\"><button class=\"btn primary\" data-action=\"resumeFirebaseSession\">${ended?'결과 다시 보기':'실시간 수업 이어보기'}</button>${ended?`<button class=\"btn\" data-action=\"clearTeacherSession\">기록 닫기</button>`:''}</div></div>`}\n""";s=s.replace(anchor,helper+anchor,1)
needle='''<p>질문, 감정 탐색, 무드미터, 만남, 삶과 연결 단계를 원하는 순서로 구성합니다. 활동은 각각 따로 보관됩니다.</p><div class="start">''';repl='''<p>질문, 감정 탐색, 무드미터, 만남, 삶과 연결 단계를 원하는 순서로 구성합니다. 활동은 각각 따로 보관됩니다.</p>${teacherSessionResumeHTML()}<div class="start">''';assert needle in s;s=s.replace(needle,repl,1)
needle=""" else if(a==='studentJoinHome'){location.href=location.pathname+'?student=1'}\n else if(a==='firebaseStudentJoin'){joinFirebaseSession()}""";repl=""" else if(a==='studentJoinHome'){location.href=location.pathname+'?student=1'}\n else if(a==='resumeFirebaseSession'){resumeFirebaseClass()}\n else if(a==='clearTeacherSession'){clearTeacherSession();render()}\n else if(a==='studentResumeRecent'){const last=readLastStudentJoin();if(last?.code)location.href=location.pathname+'?join='+encodeURIComponent(last.code)}\n else if(a==='firebaseStudentJoin'){joinFirebaseSession()}""";assert needle in s;s=s.replace(needle,repl,1)
out.write_text(s,encoding='utf-8')
new_hash=hashlib.sha256(out.read_bytes()).hexdigest();expected_out='6889fa51dfe2139ee9ce48b2b83c461decee1bc1ea121a81333d8b5fb63d73c1'
if new_hash!=expected_out: raise SystemExit(f'unexpected output hash: {new_hash}')
parts=re.findall(r'<script(?: [^>]*)?>(.*?)</script>',s,flags=re.S);Path('/tmp/drb_app.js').write_text(parts[-1],encoding='utf-8');subprocess.run(['node','--check','/tmp/drb_app.js'],check=True)
print(f'V9-5 applied: {len(s)} chars, sha256={new_hash}')
