from pathlib import Path
import hashlib
import subprocess
src=Path('index.html')
out=src
raw=src.read_bytes()
actual=hashlib.sha256(raw).hexdigest()
expected='0959baca77cd648702b4f1f9cff110f1884796189998db8f7a627f58fb877068'
if actual!=expected: raise SystemExit(f'unexpected source hash: {actual}')
s=raw.decode('utf-8')
s=s.replace('V9-6','V9-7')

css='''\n/* V9-7: classroom robustness */\n.net-pill{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:5px 8px;font-size:10px;font-weight:900;background:#edf6ef;color:#3b6b50}.net-pill.offline{background:#fff1ee;color:#8a4b43}.net-pill:before{content:'●';font-size:8px}.student-chip.stale:before{color:#c1a34b}.student-chip.stale{background:#fffaf0}.duplicate-warning{border:1px solid #efd9ad;background:#fff9ec;color:#725b2d;border-radius:11px;padding:9px 10px;font-size:10.5px;line-height:1.5;margin-top:10px}.saving-note{font-size:11px;color:#5c7181;text-align:center;margin-top:7px}.live-submit[disabled]{opacity:.55;cursor:wait}.field-stable-note{border:1px solid #d8e5ec;background:#f7fafc;border-radius:12px;padding:10px 11px;font-size:10.5px;color:#5d7485;line-height:1.5;margin-top:10px}@media(max-width:520px){.live-student-wrap{padding:8px}.live-student-card{padding:16px;border-radius:17px}.student-join-shell{padding:10px}.student-join-card{padding:18px;border-radius:18px}.session-modal{max-height:96vh}.waiting-actions .btn{flex:1 1 100%}.share-url{font-size:9px}.session-code{letter-spacing:.10em}}\n'''
s=s.replace('</style>',css+'</style>',1)
old="let fbApp=null,fbAuth=null,fbDb=null,fbSessionUnsub=null,fbParticipantsUnsub=null,fbResponsesUnsub=null,studentSessionUnsub=null,studentParticipantUnsub=null;"
new="let fbApp=null,fbAuth=null,fbDb=null,fbSessionUnsub=null,fbParticipantsUnsub=null,fbResponsesUnsub=null,studentSessionUnsub=null,studentParticipantUnsub=null,studentHeartbeatTimer=null,persistenceRequested=false;"
assert old in s;s=s.replace(old,new,1)
old="function initFirebase(){if(fbApp)return true;if(!firebaseAvailable())return false;try{fbApp=firebase.apps?.length?firebase.app():firebase.initializeApp(FIREBASE_CONFIG);fbAuth=firebase.auth();fbDb=firebase.firestore();return true}catch(e){console.error('Firebase init failed',e);return false}}"
new="function initFirebase(){if(fbApp)return true;if(!firebaseAvailable())return false;try{fbApp=firebase.apps?.length?firebase.app():firebase.initializeApp(FIREBASE_CONFIG);fbAuth=firebase.auth();fbDb=firebase.firestore();if(!persistenceRequested&&fbDb?.enablePersistence){persistenceRequested=true;fbDb.enablePersistence({synchronizeTabs:true}).catch(e=>{if(!['failed-precondition','unimplemented'].includes(e?.code))console.warn('Firestore persistence',e)})}return true}catch(e){console.error('Firebase init failed',e);return false}}"
assert old in s;s=s.replace(old,new,1)
old="function sixDigitCode(){return String(Math.floor(100000+Math.random()*900000))}\nasync function availableJoinCode(){for(let i=0;i<12;i++){const code=sixDigitCode(),snap=await fbDb.collection('joinCodes').doc(code).get();if(!snap.exists)return code}throw new Error('참여 코드를 만들지 못했습니다. 다시 시도해 주세요.')}"
new="function sixDigitCode(){return String(Math.floor(100000+Math.random()*900000))}\nasync function claimJoinCode(sessionId,teacherUid){for(let i=0;i<16;i++){const code=sixDigitCode(),ref=fbDb.collection('joinCodes').doc(code);try{await fbDb.runTransaction(async tx=>{const snap=await tx.get(ref);if(snap.exists){const e=new Error('code-taken');e.code='code-taken';throw e}tx.set(ref,{sessionId,teacherUid,createdAt:firebase.firestore.FieldValue.serverTimestamp()})});return code}catch(e){if(e?.code==='code-taken'||e?.message==='code-taken')continue;throw e}}throw new Error('참여 코드를 만들지 못했습니다. 다시 시도해 주세요.')}"
assert old in s;s=s.replace(old,new,1)
old="return {id:doc.id,name:d.name||'학생',virtual:false,status:d.status||'waiting',blockIndex:Number.isInteger(d.currentBlock)?d.currentBlock:0,joinedAt:d.joinedAt||null,meetingGroup:d.meetingGroup||null}"
new="return {id:doc.id,name:d.name||'학생',virtual:false,status:d.status||'waiting',blockIndex:Number.isInteger(d.currentBlock)?d.currentBlock:0,joinedAt:d.joinedAt||null,lastSeen:d.lastSeen||null,meetingGroup:d.meetingGroup||null}"
assert old in s;s=s.replace(old,new,1)
old="async function startFirebaseClass(){if(!state.activity)return;const errors=validateForClass(state.activity);if(errors.length){toast('사전 점검 항목을 먼저 확인해 주세요.');return}try{const teacher=await ensureTeacherAuth(),code=await availableJoinCode(),ref=fbDb.collection('sessions').doc(),now=firebase.firestore.FieldValue.serverTimestamp();await ref.set({teacherUid:teacher.uid,activityId:state.activity.id,activityTitle:state.activity.title,status:'draft',entryOpen:true,currentBlock:0,blockCount:state.activity.blocks.length,blockIds:state.activity.blocks.map(b=>b.id),activity:clone(state.activity),createdAt:now,updatedAt:now});await fbDb.collection('joinCodes').doc(code).set({sessionId:ref.id,teacherUid:teacher.uid,createdAt:now});"
new="async function startFirebaseClass(){if(!state.activity)return;const errors=validateForClass(state.activity);if(errors.length){toast('사전 점검 항목을 먼저 확인해 주세요.');return}try{const teacher=await ensureTeacherAuth(),ref=fbDb.collection('sessions').doc(),code=await claimJoinCode(ref.id,teacher.uid),now=firebase.firestore.FieldValue.serverTimestamp();await ref.set({teacherUid:teacher.uid,activityId:state.activity.id,activityTitle:state.activity.title,status:'draft',entryOpen:true,currentBlock:0,blockCount:state.activity.blocks.length,blockIds:state.activity.blocks.map(b=>b.id),activity:clone(state.activity),createdAt:now,updatedAt:now});"
assert old in s;s=s.replace(old,new,1)
old="async function endFirebaseSession(){const sess=state.sessionSetup;if(!sess||sess.mode!=='firebase'||sess.status!=='running')return;try{await updateAllFirebaseParticipants({status:'complete',lastSeen:firebase.firestore.FieldValue.serverTimestamp()});await updateFirebaseSession({status:'ended',entryOpen:false,endedAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(e){console.error(e);toast(firebaseErrorMessage(e))}}"
new="async function endFirebaseSession(){const sess=state.sessionSetup;if(!sess||sess.mode!=='firebase'||sess.status!=='running')return;try{await updateAllFirebaseParticipants({status:'complete',lastSeen:firebase.firestore.FieldValue.serverTimestamp()});await updateFirebaseSession({status:'ended',entryOpen:false,endedAt:firebase.firestore.FieldValue.serverTimestamp()});if(sess.code)await fbDb.collection('joinCodes').doc(sess.code).delete().catch(e=>console.warn('join code cleanup',e))}catch(e){console.error(e);toast(firebaseErrorMessage(e))}}"
assert old in s;s=s.replace(old,new,1)
anchor="function attachStudentSession(sessionRef,user,base){state.studentJoin=base;try{studentSessionUnsub&&studentSessionUnsub()}catch(_){}studentSessionUnsub=sessionRef.onSnapshot(snap=>{if(!snap.exists)return;const d=snap.data()||{};if(!state.studentJoin)return;Object.assign(state.studentJoin,{sessionStatus:d.status||'draft',activityTitle:d.activityTitle||state.studentJoin.activityTitle,currentBlock:Number.isInteger(d.currentBlock)?d.currentBlock:0,activity:d.activity||state.studentJoin.activity});render()});subscribeStudentParticipant(sessionRef,user.uid);subscribeStudentResponse(sessionRef,user.uid);render()}"
assert anchor in s
newanchor="function attachStudentSession(sessionRef,user,base){state.studentJoin=base;try{studentSessionUnsub&&studentSessionUnsub()}catch(_){}studentSessionUnsub=sessionRef.onSnapshot(snap=>{if(!snap.exists)return;const d=snap.data()||{};if(!state.studentJoin)return;Object.assign(state.studentJoin,{sessionStatus:d.status||'draft',activityTitle:d.activityTitle||state.studentJoin.activityTitle,currentBlock:Number.isInteger(d.currentBlock)?d.currentBlock:0,activity:d.activity||state.studentJoin.activity});if(d.status==='ended')stopStudentHeartbeat();render()});subscribeStudentParticipant(sessionRef,user.uid);subscribeStudentResponse(sessionRef,user.uid);startStudentHeartbeat(sessionRef,user.uid);render()}\nfunction stopStudentHeartbeat(){if(studentHeartbeatTimer){clearInterval(studentHeartbeatTimer);studentHeartbeatTimer=null}}\nfunction startStudentHeartbeat(sessionRef,uid){stopStudentHeartbeat();const beat=()=>{if(!navigator.onLine)return;sessionRef.collection('participants').doc(uid).update({lastSeen:firebase.firestore.FieldValue.serverTimestamp()}).catch(()=>{})};beat();studentHeartbeatTimer=setInterval(beat,45000)}\nfunction timestampMs(v){if(!v)return 0;if(typeof v.toMillis==='function')return v.toMillis();if(v.seconds)return v.seconds*1000;const n=Date.parse(v);return Number.isFinite(n)?n:0}\nfunction participantFresh(st){const ms=timestampMs(st?.lastSeen);return !ms||Date.now()-ms<120000}\nfunction duplicateStudentNames(students){const c={};(students||[]).forEach(st=>{const n=String(st.name||'').trim();if(n)c[n]=(c[n]||0)+1});return Object.entries(c).filter(([,n])=>n>1).map(([name,n])=>({name,n}))}\nfunction teacherStudentLabel(st,students){const same=(students||[]).filter(x=>x.name===st.name);if(same.length<2)return st.name;const i=same.findIndex(x=>x.id===st.id);return `${st.name} (${Math.max(0,i)+1})`}\nfunction networkPillHTML(){return `<span class=\"net-pill ${navigator.onLine?'':'offline'}\">${navigator.onLine?'연결됨':'오프라인'}</span>`}"
s=s.replace(anchor,newanchor,1)
old="const saved=studentSavedBlock(sj,b.id),head=`<div class=\"live-stage-top\"><div><span class=\"firebase-badge\">${idx+1}/${activity.blocks.length}단계</span>"
new="const saved=studentSavedBlock(sj,b.id),head=`<div class=\"live-stage-top\"><div><span class=\"firebase-badge\">${idx+1}/${activity.blocks.length}단계</span> ${networkPillHTML()}"
assert old in s;s=s.replace(old,new,1)
s=s.replace('<span class="firebase-badge">실시간 연결</span><h1>', '<span class="firebase-badge">실시간 연결</span> ${networkPillHTML()}<h1>')
old="async function saveStudentResponse(){const sj=state.studentJoin;if(!sj?.joined||sj.sessionStatus!=='running')return;const payload=collectLiveResponse();if(!payload)return;try{const user=await ensureAnonymousAuth(),ref=fbDb.collection('sessions').doc(sj.sessionId).collection('responses').doc(user.uid),ts=firebase.firestore.FieldValue.serverTimestamp();await ref.set({uid:user.uid,updatedAt:ts},{merge:true});await ref.update({[`blocks.${payload.blockId}`]:{...payload,submittedAt:ts},updatedAt:ts});toast('응답을 저장했습니다.')}catch(e){console.error(e);toast(firebaseErrorMessage(e))}}"
new="async function saveStudentResponse(){const sj=state.studentJoin;if(!sj?.joined||sj.sessionStatus!=='running')return;const payload=collectLiveResponse();if(!payload)return;const btn=document.querySelector('[data-action=\"firebaseSubmitResponse\"]');if(btn?.disabled)return;if(btn){btn.disabled=true;btn.dataset.oldText=btn.textContent;btn.textContent=navigator.onLine?'저장 중…':'연결 대기 중…'}try{const user=await ensureAnonymousAuth(),ref=fbDb.collection('sessions').doc(sj.sessionId).collection('responses').doc(user.uid),ts=firebase.firestore.FieldValue.serverTimestamp();await ref.set({uid:user.uid,updatedAt:ts},{merge:true});await ref.update({[`blocks.${payload.blockId}`]:{...payload,submittedAt:ts},updatedAt:ts});toast(navigator.onLine?'응답을 저장했습니다.':'응답을 기기에 보관했습니다. 연결되면 전송됩니다.')}catch(e){console.error(e);toast(firebaseErrorMessage(e));if(btn){btn.disabled=false;btn.textContent=btn.dataset.oldText||'응답 저장하기'}}}"
assert old in s;s=s.replace(old,new,1)
old="const online=sess.mode==='firebase',students=Array.isArray(sess.participants)?sess.participants:[],count=students.length,status=sess.status||'draft'"
new="const online=sess.mode==='firebase',students=Array.isArray(sess.participants)?sess.participants:[],duplicates=online?duplicateStudentNames(students):[],count=students.length,status=sess.status||'draft'"
assert old in s;s=s.replace(old,new,1)
old="${students.map(st=>`<div class=\"student-chip\" title=\"${esc(st.name)}\">${esc(st.name)}</div>`).join('')}"
new="${students.map(st=>`<div class=\"student-chip ${online&&!participantFresh(st)?'stale':''}\" title=\"${esc(st.name)}\">${esc(online?teacherStudentLabel(st,students):st.name)}</div>`).join('')}${online&&duplicates.length?`<div class=\"duplicate-warning\" style=\"grid-column:1/-1\"><b>같은 이름 확인</b> · ${duplicates.map(x=>`${esc(x.name)} ${x.n}명`).join(' · ')} — 현황판에서는 번호를 붙여 구분합니다.</div>`:''}"
assert old in s;s=s.replace(old,new,1)
s=s.replace('<span class="student-name">${esc(st.name)}</span>', '<span class="student-name">${esc(online?teacherStudentLabel(st,students):st.name)}</span>')
s=s.replace('<div class="completion-row"><b>${esc(st.name)}</b>', '<div class="completion-row"><b>${esc(teacherStudentLabel(st,students))}</b>')
s=s.replace('<div class="final-answer"><b>${esc(x.st.name)}</b>', '<div class="final-answer"><b>${esc(teacherStudentLabel(x.st,students))}</b>')
old="${online?`<span class=\"firebase-badge\">연결 유지</span>`:"
new="${online?`<div style=\"display:flex;gap:6px;align-items:center\"><span class=\"firebase-badge\">실시간</span>${networkPillHTML()}</div>`:"
assert old in s;s=s.replace(old,new,1)
old=" else if(a==='sessionEnd'){if(state.sessionSetup?.status!=='running')return;if(state.sessionSetup.mode==='firebase'){endFirebaseSession();return}else updateSessionState({status:'ended',entryOpen:false,endedAt:nowISO()})}"
new=" else if(a==='sessionEnd'){if(state.sessionSetup?.status!=='running')return;if(!confirm('수업을 종료할까요? 종료하면 새 학생은 더 이상 입장할 수 없습니다.'))return;if(state.sessionSetup.mode==='firebase'){endFirebaseSession();return}else updateSessionState({status:'ended',entryOpen:false,endedAt:nowISO()})}"
assert old in s;s=s.replace(old,new,1)
old="if(state.studentMode)tryRestoreStudentSession();\nrender();"
new="window.addEventListener('online',()=>{if(state.studentMode||state.sessionSetup)render()});\nwindow.addEventListener('offline',()=>{if(state.studentMode||state.sessionSetup)render()});\ndocument.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.studentJoin?.joined&&fbAuth?.currentUser?.isAnonymous){const ref=fbDb.collection('sessions').doc(state.studentJoin.sessionId);startStudentHeartbeat(ref,fbAuth.currentUser.uid)}});\nif(state.studentMode)tryRestoreStudentSession();\nrender();"
assert old in s;s=s.replace(old,new,1)
out.write_text(s,encoding='utf-8')
new_hash=hashlib.sha256(out.read_bytes()).hexdigest();expected_out='860bac06b9b680c8376b2d814d34fc64d4c59b7bf7a3db83703ae711648d71b1'
if new_hash!=expected_out: raise SystemExit(f'unexpected output hash: {new_hash}')
import re as _re
parts=_re.findall(r'<script(?: [^>]*)?>(.*?)</script>',s,flags=_re.S);Path('/tmp/drb_app.js').write_text(parts[-1],encoding='utf-8');subprocess.run(['node','--check','/tmp/drb_app.js'],check=True)
print(f'V9-7 applied: {len(s)} chars, sha256={new_hash}')
