(()=>{
  const V990='V9-9.0';
  function uniq(xs){return [...new Set((xs||[]).map(x=>String(x||'').trim()).filter(Boolean))]}
  function sourceMode(b){return b?.emotionSource==='independent'?'independent':'mood'}
  function moodCandidates(b,x,y){return uniq([...moodHintWords({x,y}),...((b?.emotionLabels)||[])])}
  function prevMood(sj,idx){const bs=sj?.activity?.blocks||[];for(let i=Math.min(idx-1,bs.length-1);i>=0;i--){const b=bs[i];if(b?.type!=='mood')continue;const r=studentSavedBlock(sj,b.id);if(!r)continue;return {block:b,response:r,selected:uniq(r.selectedEmotions||[]).slice(0,2)}}return null}
  function independentWords(b){return uniq(['기쁨','편안함','걱정','화남','서운함','긴장','당황','외로움','복잡함',...((b?.emotionLabels)||[])])}
  function linkedBox(words){const w=uniq(words).slice(0,2);return w.length?`<div class="v990-linked"><b>앞선 무드미터에서 고른 마음</b><div class="v990-linked-chips">${w.map(x=>`<span>${esc(x)}</span>`).join('')}</div><small>이 마음을 이어서 강도·몸의 신호·행동 충동·이유를 살펴봅니다.</small></div>`:''}
  const css=document.createElement('style');css.textContent=`
  .v990-mood-words{margin-top:12px;padding-top:10px;border-top:1px dashed #d7e2e9}.v990-mood-words>small{display:block;text-align:center;color:#718493;margin-bottom:8px;font-weight:750}.v990-word-grid{display:flex;flex-wrap:wrap;gap:7px;justify-content:center}.v990-word-grid button,.v990-linked-chips span{border:1px solid #d8e3e9;background:#fff;border-radius:999px;padding:8px 11px;font-weight:800;color:#40586d}.v990-word-grid button{cursor:pointer}.v990-word-grid button.live-selected{background:#eef7ff;border-color:#62a3d1;box-shadow:inset 0 0 0 1px #62a3d1}.v990-linked{border:1px solid #cfe1ed;background:#f5fbff;border-radius:14px;padding:12px;margin-bottom:12px}.v990-linked b{display:block;margin-bottom:7px;color:#244e67}.v990-linked-chips{display:flex;flex-wrap:wrap;gap:7px}.v990-linked small,.v990-source-note{font-size:11px;line-height:1.5;color:#6f8292}.v990-source-note{margin:8px 0;padding:8px 10px;border-radius:10px;background:#f4f8fb}.student-themed .v990-word-grid button,.student-themed .v990-linked-chips span{background:var(--student-option)!important;color:var(--student-text)!important}.student-themed .v990-word-grid button.live-selected{border-color:var(--student-accent)!important;background:color-mix(in srgb,var(--student-accent) 12%,var(--student-option))!important}.student-themed .v990-linked{background:var(--student-panel)!important}.student-themed .v990-linked b{color:var(--student-title)!important}`;document.head.appendChild(css);

  const oldNewBlock=newBlock;newBlock=function(type){const b=oldNewBlock(type);if(type==='emotion'){b.emotionSource='mood';b.emotionLabels=b.emotionLabels||[]}if(type==='mood'&&b.pickEmotions===undefined)b.pickEmotions=true;return b};
  const oldSampleEmotion=sampleEmotion;sampleEmotion=function(){const a=oldSampleEmotion();const m=a.blocks.find(x=>x.type==='mood'),e=a.blocks.find(x=>x.type==='emotion');if(m)m.pickEmotions=true;if(e){e.emotionSource='mood';e.emotionLabels=e.emotionLabels||[]}return a};

  const oldBasic=basicSettings;basicSettings=function(b){let h=oldBasic(b);if(b.type==='emotion')h+=`<div class="setting-section"><h4>감정 탐색 시작점</h4><div class="radio-grid"><div class="radio ${sourceMode(b)==='mood'?'on':''}" data-emotion-source="mood">앞선 무드미터와 연결</div><div class="radio ${sourceMode(b)==='independent'?'on':''}" data-emotion-source="independent">독립적으로 탐색</div></div><div class="tiny-note" style="margin-top:9px">연결 모드는 앞선 무드미터에서 학생이 고른 감정 1~2개를 그대로 가져와 강도·몸·행동·이유를 더 깊게 살펴봅니다. 앞선 응답이 없으면 직접 선택 화면으로 전환됩니다.</div></div>`;if(b.type==='mood')h+=`<div class="setting-section"><div class="switchline"><div><h4 style="margin:0">좌표 뒤 감정어 선택</h4><div class="tiny-note">가까운 감정어와 교사가 추가한 감정어 중 최대 2개를 고릅니다.</div></div><div class="switch ${b.pickEmotions!==false?'on':''}" data-toggle="pickEmotions"></div></div></div>`;return h};
  const oldContent=contentSettings;contentSettings=function(b){let h=oldContent(b);if(b.type==='emotion')h+=listEditor('독립 탐색에 추가할 감정어','emotionLabels',b.emotionLabels||[],'감정어 추가')+`<div class="tiny-note">독립 탐색에서 기본 감정어와 함께 표시됩니다. 무드미터 연결 모드에서는 앞선 단계에서 실제로 고른 감정을 이어받습니다.</div>`;if(b.type==='mood')h+=`<div class="tiny-note" style="margin-top:10px">추가 감정어도 실제 학생 화면에 표시되며, 학생이 고른 감정은 뒤의 연결된 감정 탐색으로 이어집니다.</div>`;return h};
  const oldEmotionInner=emotionInner;emotionInner=function(kind,b){if(kind==='emotion'&&sourceMode(b)==='mood')return `<div class="v990-linked"><b>앞선 무드미터에서 고른 마음 <span class="example-badge">실제 수업에서 연결</span></b><div class="v990-linked-chips"><span>서운함</span><span>답답함</span></div><small>실제 수업에서는 그 학생이 앞 단계에서 고른 감정 1~2개가 이어집니다.</small></div>`;return oldEmotionInner(kind,b)};

  const oldLive=liveStudentBlockHTML;liveStudentBlockHTML=function(sj){const activity=sj?.activity,idx=Math.max(0,Math.min((activity?.blocks?.length||1)-1,Number(sj?.currentBlock)||0)),b=activity?.blocks?.[idx];if(!b||!['mood','emotion'].includes(b.type))return oldLive(sj);const saved=studentSavedBlock(sj,b.id),head=`<div class="live-stage-top"><div><span class="firebase-badge">${idx+1}/${activity.blocks.length}단계</span> ${networkPillHTML()}<h2 style="margin:8px 0 0">${esc(b.title||b.name)}</h2></div><small>${esc(catalog[b.type]?.label||b.type)}</small></div>`;let body='';
    if(b.type==='mood'){const x=Number(saved?.x),y=Number(saved?.y),has=Number.isFinite(x)&&Number.isFinite(y),selected=uniq(saved?.selectedEmotions||[]).slice(0,2),cand=has?moodCandidates(b,x,y):[];body=`<div class="live-question"><p>${esc(b.note||'마음의 위치를 눌러보세요.')}</p><div class="live-mood-map" data-live-mood data-x="${has?x:''}" data-y="${has?y:''}" role="button" tabindex="0"><i class="live-mood-dot" style="${has?`display:block;left:${x*100}%;top:${y*100}%`:''}"></i></div><div class="live-mood-hint" data-live-mood-hint>${has?`이 근처의 마음 · <b>${moodHintWords({x,y}).map(esc).join(' · ')}</b>`:'마음지도에서 내 위치를 눌러보세요.'}</div>${b.pickEmotions!==false?`<div class="v990-mood-words" data-live-mood-emotions>${has?`<small>가까운 마음말과 선생님이 더한 말 중 최대 2개를 골라보세요.</small><div class="v990-word-grid">${cand.map(w=>`<button type="button" class="${selected.includes(w)?'live-selected':''}" data-live-mood-emotion="${esc(w)}">${esc(w)}</button>`).join('')}</div>`:'<small>먼저 마음지도에서 위치를 선택하면 감정어가 나타납니다.</small>'}</div>`:''}</div>`}
    else {const ctx=sourceMode(b)==='mood'?prevMood(sj,idx):null,linked=ctx?.selected||[],savedWords=uniq(saved?.emotions||(saved?.emotion?[saved.emotion]:[])),words=independentWords(b);body=`${linkedBox(linked)}${b.steps?.emotion!==false&&!linked.length?`<div class="live-question"><b>${esc(b.emotionPrompt||'지금 마음과 가까운 감정은 무엇인가요?')}</b><div class="v990-source-note">${sourceMode(b)==='mood'?'앞선 무드미터에 선택된 감정어가 없어 여기에서 직접 고릅니다. ':''}최대 2개까지 선택할 수 있습니다.</div><div class="live-emotion-grid">${words.map(x=>`<button class="${savedWords.includes(x)?'live-selected':''}" data-live-emotion="${esc(x)}">${esc(x)}</button>`).join('')}</div></div>`:''}${b.steps?.intensity!==false?`<div class="live-question"><b>${esc(b.intensityPrompt||'그 감정은 얼마나 강했나요?')}</b><div class="live-intensity">${[1,2,3,4,5].map(n=>`<button class="${saved?.intensity===n?'live-selected':''}" data-live-intensity="${n}">${n}</button>`).join('')}</div></div>`:''}${b.steps?.body!==false?`<div class="live-question"><b>${esc(b.bodyPrompt||'몸에서는 어떤 신호가 있었나요?')}</b><div class="live-chips">${['가슴이 두근거림','배가 답답함','얼굴이 뜨거움','손에 힘이 들어감','몸이 굳는 느낌'].map(x=>`<button class="${saved?.body===x?'live-selected':''}" data-live-body="${esc(x)}">${esc(x)}</button>`).join('')}</div></div>`:''}${b.steps?.impulse!==false?`<div class="live-question"><b>${esc(b.impulsePrompt||'그때 무엇을 하고 싶었나요?')}</b><div class="live-chips">${['말하고 싶었어요','자리를 피하고 싶었어요','가만히 있고 싶었어요','도움을 청하고 싶었어요','따지고 싶었어요','다시 해보고 싶었어요'].map(x=>`<button class="${saved?.impulse===x?'live-selected':''}" data-live-impulse="${esc(x)}">${esc(x)}</button>`).join('')}</div></div>`:''}${b.steps?.reason!==false?`<div class="live-question"><b>${esc(b.reasonPrompt||'왜 그렇게 느꼈다고 생각하나요?')}</b><textarea data-live-reason placeholder="내 말로 적어보세요">${esc(saved?.reason||'')}</textarea></div>`:''}`}
    return `${head}${body}<button class="live-submit ${saved?'saved':''}" data-action="firebaseSubmitResponse">${saved?'응답 다시 저장하기':'응답 저장하기'}</button>${saved?`<div class="live-saved-note">이 단계 응답이 저장되어 있습니다. 다시 저장하면 최신 내용으로 바뀝니다.</div>`:''}`};

  const oldCollect=collectLiveResponse;collectLiveResponse=function(){const sj=state.studentJoin,activity=sj?.activity,idx=Number(sj?.currentBlock)||0,b=activity?.blocks?.[idx];if(!b||!['mood','emotion'].includes(b.type))return oldCollect();const base={type:b.type,blockIndex:idx,blockId:b.id};if(b.type==='mood'){const map=document.querySelector('[data-live-mood]'),x=Number(map?.dataset.x),y=Number(map?.dataset.y);if(!Number.isFinite(x)||!Number.isFinite(y)){toast('마음지도에서 위치를 선택해 주세요.');return null}const selectedEmotions=uniq([...document.querySelectorAll('[data-live-mood-emotion].live-selected')].map(el=>el.getAttribute('data-live-mood-emotion'))).slice(0,2);if(b.pickEmotions!==false&&!selectedEmotions.length){toast('가까운 마음말을 1개 이상 골라 주세요.');return null}return {...base,x,y,words:moodHintWords({x,y}).slice(0,4),selectedEmotions}}const ctx=sourceMode(b)==='mood'?prevMood(sj,idx):null,linked=ctx?.selected||[],picked=uniq([...document.querySelectorAll('[data-live-emotion].live-selected')].map(el=>el.getAttribute('data-live-emotion'))).slice(0,2),emotions=linked.length?linked:picked,out={...base},i=oneSelected('data-live-intensity'),body=oneSelected('data-live-body'),imp=oneSelected('data-live-impulse'),reason=document.querySelector('[data-live-reason]')?.value.trim()||'';if(emotions.length){out.emotions=emotions;out.emotion=emotions[0]}if(ctx&&linked.length){out.moodSourceBlockId=ctx.block.id;out.moodSource={x:ctx.response.x,y:ctx.response.y}}if(i)out.intensity=Number(i);if(body)out.body=body;if(imp)out.impulse=imp;if(reason)out.reason=reason;if(Object.keys(out).length<=3){toast('한 가지 이상 응답해 주세요.');return null}return out};

  function bindMulti(sel,max=2){document.querySelectorAll(sel).forEach(el=>el.onclick=e=>{e.preventDefault();const picked=[...document.querySelectorAll(`${sel}.live-selected`)];if(el.classList.contains('live-selected')){el.classList.remove('live-selected');return}if(picked.length>=max){toast(`감정은 최대 ${max}개까지 선택할 수 있습니다.`);return}el.classList.add('live-selected')})}
  const oldBindLive=bindLiveStudentInputs;bindLiveStudentInputs=function(){oldBindLive();bindMulti('[data-live-emotion]');bindMulti('[data-live-mood-emotion]');document.querySelectorAll('[data-live-mood]').forEach(map=>{const choose=e=>{const r=map.getBoundingClientRect(),cx=e.touches?.[0]?.clientX??e.clientX,cy=e.touches?.[0]?.clientY??e.clientY,x=Math.max(.02,Math.min(.98,(cx-r.left)/r.width)),y=Math.max(.02,Math.min(.98,(cy-r.top)/r.height));map.dataset.x=x;map.dataset.y=y;const dot=map.querySelector('.live-mood-dot');if(dot){dot.style.display='block';dot.style.left=x*100+'%';dot.style.top=y*100+'%'}const hint=document.querySelector('[data-live-mood-hint]');if(hint)hint.innerHTML=`이 근처의 마음 · <b>${moodHintWords({x,y}).map(esc).join(' · ')}</b>`;const b=state.studentJoin?.activity?.blocks?.[Number(state.studentJoin?.currentBlock)||0],box=document.querySelector('[data-live-mood-emotions]');if(box&&b?.pickEmotions!==false){const cand=moodCandidates(b,x,y);box.innerHTML=`<small>가까운 마음말과 선생님이 더한 말 중 최대 2개를 골라보세요.</small><div class="v990-word-grid">${cand.map(w=>`<button type="button" data-live-mood-emotion="${esc(w)}">${esc(w)}</button>`).join('')}</div>`;bindMulti('[data-live-mood-emotion]')}};map.onclick=choose;map.ontouchstart=e=>{e.preventDefault();choose(e)}})};

  const oldBind=bind;bind=function(){oldBind();document.querySelectorAll('[data-emotion-source]').forEach(el=>el.onclick=()=>{current().emotionSource=el.dataset.emotionSource==='independent'?'independent':'mood';autosave();render()})};
  const oldValidate=validateForClass;validateForClass=function(a){const errs=oldValidate(a);(a?.blocks||[]).forEach((b,i)=>{if(b.type==='emotion'&&sourceMode(b)==='mood'&&!a.blocks.slice(0,i).some(x=>x.type==='mood'))errs.push(`${i+1}단계(감정 탐색)는 앞선 무드미터와 연결되어 있지만 앞쪽에 무드미터 단계가 없습니다.`)});return errs};
  document.querySelectorAll('.version-badge').forEach(el=>el.textContent=V990);try{render()}catch(e){console.error('V9-9.0 patch render',e)}
})();
